### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by alexbilbie** [aws/aws-xray-sdk-go#1]
After some experimentation I've been able to successfully integrate this into my application, thank you!

After the "Configuration" section and before the "Capture" section in the README's Quick Start can I recommend adding a simple example of how to start a segment and subsegment for those developers who aren't working with HTTPS based services:

```go
// Start a segment:
ctx, seg := xray.BeginSegment(context.Background(), "my-service-name")

ctx, subSeg := xray.BeginSubsegment(ctx, "Some unit of work")
// ...
// some unit of work here
// ...
subSeg.Close(nil)

// Close the segment
seg.Close(nil)
```

**Comment by luluzhao** [comment]
@alexbilbie , we released a new version of SDK which contains your suggestions. Thank you for your suggestion.
