### ISSUE TITLE
Traced http.Client should allow requests without a segment to proceed

### ISSUE THREAD

**Issue by NZKoz** [aws/aws-xray-sdk-go#10]
I'm currently migrating from our own home-grown (and less featured) xray sdk to the official one, and have hit a slightly annoying limitation.  We had an http.Client that was *mostly* used for inline requests, but also would occasionally be provided with an out of context request.  Those out of context requests all failed with [this error](https://github.com/aws/aws-xray-sdk-go/blob/6db6b3f2eca9a1fc1ec2d9998c07f82e526ec237/xray/httptrace.go#L167):

```go
	if opCtx == nil {
		return nil, errors.New("opCtx must be non-nil")
	}
```

While it certainly simplifies the implementation, it would be much nicer if we could reliably make HTTP requests and simply have the tracing skipped when there's no segment in the context.

**Comment by luluzhao** [comment]
@NZKoz we released version 0.9.4 which gonna solve your problem. Feel free to pull the newest release version of our SDK and tell us if it still haven't solved your problem. If it works good. Could you please close this issue? Thank you.

**Comment by NZKoz** [comment]
I'll try it today

**Comment by luluzhao** [comment]
@NZKoz , have you tried our new version of X-Ray Go SDK? I am going to close this issue since it haven't been updated for about one month. Feel free to reopen it if it's not working for your application. Thank you.
