### ISSUE TITLE
Remove package global state

### ISSUE THREAD

**Issue by cep21** [aws/aws-xray-sdk-go#11]
Hi,

I understand this is currently just in beta.  Are you open to rethinking the API?  I work at twitch, and forked a similar library to remove package global state.  You can read more about package global state at https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables or https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html

I worry the library, currently designed, forces a large amount of global mutable state which could limit usage.

The library also requires an import tree that's often too deep for many Go libraries.  The library I originally forked (which is very similar to this one) I modified to remove those dependencies: particularly github.com/aws/aws-sdk-go

I would strongly prefer the following changes:

1) Remove global mutable state.  This includes configuration and (it appears) the logging library used.
2) Remove dependency on github.com/aws/aws-sdk-go from xray core.  There are many Go services that don't use the AWS sdk because they don't talk to DynamoDB, etc, and it would be a shame to force them to import such a heavy package chain.

Please let me know if you're open, and if I can be of help with either of these.

Thanks!

**Comment by Kaidence** [comment]
Hi! I'd like to echo cep21's concerns. We'd love to be on the main x-ray library, though. Is this something your team is actively working on? Do you accept PRs?

**Comment by luluzhao** [comment]
@Kaidence , we are working on it right now and hopefully it will be released soon. We do accept PRs and feel free send it. Thank you.

**Comment by cep21** [comment]
Hi,

Looking forward to using x-ray.  Any update on this task?

Thanks!

**Comment by luigi-riefolo** [comment]
@luluzhao what's the state of this feature?

**Comment by bhautikpip** [comment]
Hi @luigi-riefolo,

We have merged this PR about logging interface (https://github.com/aws/aws-xray-sdk-go/pull/82). I think we still need to prioritize removing global mutable state and removing deep dependencies tree in Xray Go SDK design.

**Comment by luigi-riefolo** [comment]
@bhautikpip can we close this PR then?

**Comment by bhautikpip** [comment]
Hi @luigi-riefolo,

I think we can keep this open as a reference point if that's okay.

**Comment by bhautikpip** [comment]
Hi @cep21,

As we are prioritizing this efforts, would you mind providing any code path where we can start addressing global mutable state concerns in XRay Go SDK ? Also, really appreciate for any design ideas to remove deep dependency tree.

**Comment by luigi-riefolo** [comment]
@bhautikpip @cep21 the library has significantly changed since this issue was created.
We first need to list all files that still have global states

**Comment by cep21** [comment]
I can't give input since i don't use the library anymore.  If you've made improvements,  that's great news!

**Comment by bhautikpip** [comment]
Hi @luigi-riefolo,

Yes. That's a good starting point. We have tried to remove it wherever we can. That's why I have posted this question to seek feedback from library users to get some more pointers on where we see global states and removing from there would be a good idea.

**Comment by bhautikpip** [comment]
Hi,

Thank you all for opening this issue. Since GA release we have tried to cover this point and try to reduce global states in the library wherever it's possible. I am closing this issue since it's very old. Feel free to open new one if we can improve at any other place in the library. Thanks again!
