### ISSUE TITLE
xray handler for grpc 

### ISSUE THREAD

**Issue by rvdwijngaard** [aws/aws-xray-sdk-go#110]
Do you have any plans for adding xray handler for grpc servers / clients?

**Comment by ss2305** [comment]
Hi Ron,

Currently we do not have support for grpc but we will add it into our backlogs. Can you share examples of use cases you are trying to tackle? 
Meanwhile we do welcome PRs and would be happy to review. 

Best Regards
Srikant

**Comment by shubharao** [comment]
App Mesh customers are asking for this: https://github.com/aws/aws-app-mesh-roadmap/issues/256

**Comment by srprash** [comment]
Hi @rvdwijngaard 
We have this feature request added to our backlog. We would try to pull it in to work on as soon as possible. 
Thanks for your patience and please stay tuned!

**Comment by JustinEdwardKennedy** [comment]
Created https://github.com/vendrive/xray-grpc for temporary use while https://github.com/aws/aws-xray-sdk-go/pull/264 makes its way through.

**Comment by bhautikpip** [comment]
Instrumentation unary gRPC support is merged and released in `v1.5.0` release so closing out this issue.
