### ISSUE TITLE
RFC: backwards incompatible change to BeginSubsegment: remove goroutine

### ISSUE THREAD

**Issue by cep21** [aws/aws-xray-sdk-go#116]
I would like to propose a backwards incompatible change to BeginSubsegment while the client is in RC and get community feedback.

We should remove the goroutine created inside `BeginSegment`.  The line referenced is https://github.com/aws/aws-xray-sdk-go/blob/de6489788fd3cac48c982c3d304120bbd9049d6c/xray/segment.go#L70

The API remains the same, but users will be required to call `Close` on the returned segment when they are done with it, if they want to send it to x-ray.

The downside of this change is that users will not be able to call `BeginSegment` and rely on it being flushed when the Segment is closed.

The upside is
1. Correct implementations of x-ray and users of `BeginSegment` should ensure to call Close anyways.
2. There have been a few issues on the tracker in the past on goroutines being stuck on this select, or bugs caused by this goroutine
3. Probably most importantly, it is a not negligible amount of overhead to spawn a new goroutine for each segment: including segments that are sampled away and never sent to x-ray at all.

**Comment by luluzhao** [comment]
#51
