### ISSUE TITLE
StreamingStrategy documentation missing

### ISSUE THREAD

**Issue by lsuss** [aws/aws-xray-sdk-go#12]
I'm doing some experiments with this sdk and found out that StreamingStrategy isn't documented yet.

Hard to understand what this is for (stream subsegment I guess) and if it is supported yet (returning true for RequiresStreaming doesn't seems to stream anything).

**Comment by luluzhao** [comment]
Hi @lsuss , thank you for reaching out to us. Have you checked our public documentation for Go? Here I attached the link: http://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-configuration.html . Let me know if you have any comments on this.

**Comment by lsuss** [comment]
Thank you for response. I didn't saw it in the documentation at first sight, my bad :(.

Little comment: There is no mention of "StreamCompletedSubsegments".
