### ISSUE TITLE
Does xray DB tracer work?

### ISSUE THREAD

**Issue by masahiro331** [aws/aws-xray-sdk-go#120]
Hi. Thank you for good SDK!!!

I have problem, please help. 

Environment 
On:   EC2 (Amazon linux2)
Run:  Xray daemon (2.1.3)
DB: Postgresql (docker postgres:9.6)
GO:  go1.12.5 linux/amd64
SDK: github.com/aws/aws-xray-sdk-go@v1.0.0-rc.11

I wrote code as below.
```
func main() {
        db, err := xray.SQL("postgres", "user=postgres password=postgres dbname=postgres sslmode=disable")
        if err != nil {
                fmt.Printf("%+v", err)
        }
        defer db.Close()

        var res string
        ctx, _ := xray.BeginSegment(context.Background(), "db-controller")
        err = db.QueryRow(ctx, "SELECT name from users;").Scan(&res)
        if err != nil {
                fmt.Printf("failed to error %+v\n", err)
        }
        fmt.Print(res)
}
```

I can't get metrics on aws console  「X-Ray Service Map」. 
And xray-daemon nothing log.

**Comment by masahiro331** [comment]
I'm sorry. I fixed this issue. SQL trace is subsegment... 
Can I fixed example code? I think that is very old ...

**Comment by masahiro331** [comment]
Fix code: 
func main() {
        db, err := xray.SQL("postgres", "user=postgres password=postgres dbname=postgres sslmode=disable")
        if err != nil {
                fmt.Printf("%+v", err)
        }
        defer db.Close()

        var res string
        ctx, seg := xray.BeginSegment(context.Background(), "db-controller")
        err = db.QueryRow(ctx, "SELECT name from users;").Scan(&res)
        if err != nil {
                fmt.Printf("failed to error %+v\n", err)
        }
        fmt.Print(res)
        seg.Close(nil) // Add this code. 
}

**Comment by luluzhao** [comment]
@masahiro331, thank you for contacting us regarding your question. Tracing SQL operations will be subsegments. Do you mean you want to fix the example listing on our README.

**Comment by masahiro331** [comment]
Yes. And this repository https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/src/colorteller/main.go

**Comment by luluzhao** [comment]
@masahiro331 feel free to send out PR about fixing the example in README. Regarding this [link](https://github.com/aws/aws-app-mesh-examples/blob/master/examples/apps/colorapp/src/colorteller/main.go), I am not sure what do you mean. That repo is managed by App Mesh team. If you want to contribution to that repo, you can also submit PR or open an issue for that.

**Comment by masahiro331** [comment]
Thanks you! @luluzhao 
I cloes this issue.
