### ISSUE TITLE
Clarify use of defer/recover pattern inside `strategy/sampling`

### ISSUE THREAD

**Issue by cep21** [aws/aws-xray-sdk-go#124]
There are a few `defer ... r := recover()` statements inside `/strategy/sampling`.  Blanket defer/recover statements are a very bad pattern in Go code because they can mask deeper issues inside the functions they wrap.  Ideally none of the code inside strategy/sampling would panic.  Can we investigate why these defer/recover are needed and if there is some root issues inside strategy/sampling that are causing a panic we can resolve instead?

**Comment by luluzhao** [comment]
The reason why we want to recover from panic is that everything happened inside strategy/sampling shouldn't block customer's application. If centralized sampling has some errors causing panic, the rulePoller and targetPollor threads die silent with error message logged and then fall back to localized sampling strategy. Yes, ideally none of the code inside strategy/sampling should panic. However, if it panics, customer shouldn't bother with it and sampling strategy will still be applied just different one.

**Comment by cep21** [comment]
> The reason why we want to recover from panic is that everything happened inside strategy/sampling shouldn't block customer's application.

That's a good reason to use goroutines and I agree with that, but I don't think the `defer/recover` pattern used is required to prevent blocking.

> However, if it panics, customer shouldn't bother with it and sampling strategy will still be applied just different one.

I understand that, but it's generally considered bad practice and a code smell.  Do you have examples of other Go libraries that take similar approaches.  It usually happens when library code calls out to user injected functions or callbacks, but I've never seen it when library code calls itself.

**Comment by luluzhao** [comment]
I think this is the design logic we follow when we design centralized sampling strategy and here is the reference from [java](https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/strategy/sampling/pollers/RulePoller.java#L43). I don't know whether other Go libraries have similar design logic or not. Do you have any suggestions how to handle this issue? I mean is there any other better way to handle the panic without blocking customer's application?

**Comment by cep21** [comment]
> I mean is there any other better way to handle the panic without blocking customer's application?

Since it's a goroutine, customer code won't block.

> here is the reference from java.

Java has only one way to handle errors: exceptions.  Sometimes exceptions are used for expected errors, like IO timeouts or file permissions.  Sometimes they are used for mostly unrecoverable things, like out of heap space, and sometimes they are used for software bugs, like null pointer exceptions.  Independent of the use cases for errors, Java has checked and unchecked exceptions.  While generally people prefer checked exceptions to be used for the expected errors, this advice is often ignored and you end up with expected errors being unchecked exceptions that throw up the call stack.  That's why people put the `catch (Throwable t)` stuff around Java code.

Go has two classes of errors: `type error interface` and panic.  The error interface is used for expected errors and `panic` is used for the mostly unrecoverable or software bug side of errors.  Because of this, there's no need to generally wrap goroutines inside `defer/recover` blocks since expected errors of all kinds should be a `error` return value.

The `defer/recover` pattern is however often used in Go libraries when your application calls out to injected functions or libraries.  An example of this is Go's http.Server, which takes a [handler](https://golang.org/pkg/net/http/#Handler) as a parameter.  The code of the handler isn't written by the Go standard library: it's written by a third party and injected into the handler to handle requests.  So Go's http server does a defer/recover to execute this third party code.

There are other examples of Go's http code spawning goroutines, like [here](https://github.com/golang/go/blob/go1.12.5/src/net/http/transport.go#L980), without defer/recover.  Go does not wrap every goroutine with a defer/recover because these are calling the go stdlib's code itself.

These calls of `defer/recover` are only used around x-ray library code.  By wrapping your own code in `defer/recover` you're communicating a distrust of your own code because the only reasonable things that could happen here are software bugs, like nil pointers or double mutex unlocking.

**Comment by luluzhao** [comment]
@cep21 sorry for the late reply. If we remove the `defer/recover` from the go routine and there is a panic inside `refreshTargets` or `refreshManifest` method, the program will stop, is that correct? Inside our code, we capture the [error](https://github.com/aws/aws-xray-sdk-go/blob/master/strategy/sampling/centralized.go#L257) and log it. Even if there is something wrong inside our code, at least we keep track of it and then customer's application is still working except there is no centralized sampling in that case. If we remove it, even this is a go routine, the panic will still block the rest of the program. We just want to make sure our centralized sampling won't panic customer's application even if there were some bugs inside our implementation.

I am wondering what is your proposal regarding this situation? If we remove the `defer/recover` and there is a panic inside xray library, how could we guarantee that customer's application won't be blocked?

**Comment by cep21** [comment]
> the program will stop, is that correct

Yes

> how could we guarantee that customer's application won't be blocked

It wouldn't.

Are you proposing that all Go libraries that spawn non-trivial goroutines wrap the `go` function in defer/recover?  The majority do not.  It seems like every library would want this guarantee.

**Comment by luluzhao** [comment]
However, this is the decision we make when we design it. Something wrong happened inside `refreshTargets` or `refreshManifest`, it will die silently instead of stopping customer's application.
