### ISSUE TITLE
Multiple subsegments, not sending

### ISSUE THREAD

**Issue by davidhopkins** [aws/aws-xray-sdk-go#130]
Either I am misunderstanding subsegments or there seems to be a bug when you create more than one:

```go
func main() {
	xray.Configure(xray.Config{
		DaemonAddr: "localhost:2000",
	})
	xray.SetLogger(xraylog.NewDefaultLogger(os.Stdout, xraylog.LogLevelDebug))

	ctx, segment := xray.BeginSegment(context.Background(), "s")

	ctx, subseg1 := xray.BeginSubsegment(ctx, "ss1")
	subseg1.Close(nil)

	ctx, subseg2 := xray.BeginSubsegment(ctx, "ss2")
	subseg2.Close(nil)

	segment.Close(nil)
}
```
Results in *no* trace being sent to the daemon despite the logs indicating all is OK:

```
2019-07-10T15:28:39+01:00 [INFO] Emitter using address: 127.0.0.1:2000
2019-07-10T15:28:39+01:00 [DEBUG] Beginning segment named s
2019-07-10T15:28:39+01:00 [DEBUG] Beginning subsegment named ss1
2019-07-10T15:28:39+01:00 [DEBUG] Beginning subsegment named ss2
2019-07-10T15:28:39+01:00 [DEBUG] Closing subsegment named ss2
2019-07-10T15:28:39+01:00 [DEBUG] Closing segment named s
```
However if I remove subseg1 or subseg2 then it works just fine. Thoughts?

**Comment by luluzhao** [comment]
Hi @davidhopkins , thank you for contacting us regarding your issue. The reason why it is not working is that the `ctx` you provide is not correct. In go sdk, all the segments/subsegments are injected into `context` to propagate. In your example, you created a segment called `s` and then injected it into `context.Background()`. Then the `ctx` contains the segment that you just created. However, in your first `BeginSubsegment` method, you reused the `ctx` as the result of this method which now contained a subsegment and then you passed it into another `BeginSubsegment` method and try to create another subsegment. The problem coming here is that you cannot create subsegment `ss2` based on a closed `ss1`. If you want segment `s` contains two subsegments `ss1` and `ss2`, there is the example below.

```
	ctx, segment := xray.BeginSegment(context.Background(), "s")
	_, subseg1 := xray.BeginSubsegment(ctx, "ss1")
	subseg1.Close(nil)
	_, subseg2 := xray.BeginSubsegment(ctx, "ss2")
	subseg2.Close(nil)
	segment.Close(nil)
```

Please let me if you still have questions.

**Comment by davidhopkins** [comment]
Thanks for the help!
