### ISSUE TITLE
Password not removed when connecting to MySQL

### ISSUE THREAD

**Issue by zijima** [aws/aws-xray-sdk-go#131]
Hi,

I'm trying to open a new SQL connection this [required DSN format:](https://github.com/go-sql-driver/mysql#dsn-data-source-name): 

> user:password@(host:port)/database

However, the password section is not removed from connection string therefore i'm able to see the full DSN, including pwd, when i open traces in AWS XRay service Console. 

Looks like [current code](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/sql_test.go#L115) can handle case like:

> user:password@host:port/database

But not the one with `()`

Source code also mentioned current [logic is based on surveys from 2017. ](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/sql.go#L78)

Any chance you can include parsing the DSN format i needed?

thanks

**Comment by luluzhao** [comment]
@zijima thank you for contacting us regarding your issue. We will add this into our backlog and in the meantime, A PR is always welcomed.

**Comment by zijima** [comment]
It turns out that my DSN failed [url.parse](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/sql.go#L42) because my password has characters like `[` and `]` which is treated as [invalid user info](https://github.com/golang/go/blob/master/src/net/url/url.go#L1102)  :(

i have a suggestion to handle the `net/url: invalid userinfo` error and remove password from the url

**Comment by bhautikpip** [comment]
Hi @zijima,

We have recently merged one PR which solves this issue (https://github.com/aws/aws-xray-sdk-go/pull/169/files#diff-5bba2290697477468cb32ac08c47bd3aR733). So, I am closing this issue for now. Feel free to reopen an issue if you see any more issues.
