### ISSUE TITLE
Support for fasthttp

### ISSUE THREAD

**Issue by fpruitt2** [aws/aws-xray-sdk-go#133]
## Background
`fasthttp` is an alternative to Go's native `net/http` network library. It is written to be significantly more performant at scale; in some cases, it is ~10x faster than the standard library. It is used widely and is well-maintained.

## The Ask
It would be helpful if `aws-xray-sdk-go`  could work out-of-the-box with `fasthttp`. The interface in the request handlers is different enough to make it not trivial to use as-is. 

## Links
[fasthttp](https://github.com/valyala/fasthttp)
[net/http-->fasthttp adaptor](https://github.com/valyala/fasthttp/blob/master/fasthttpadaptor/adaptor.go)

**Comment by ss2305** [comment]
@fpruitt2 We appreciate your input and will consider adding it to our roadmap.

**Comment by fpruitt2** [comment]
An acceptable alternative would be decoupling the tracking of a request's data from a specific http library-- being able to (easily) manually set up request tracking would be great!

**Comment by ss2305** [comment]
@fpruitt2 We would be happy to review any PRs if you want to contribute on this.

**Comment by bhautikpip** [comment]
fasthttp instrumentation support PR (https://github.com/aws/aws-xray-sdk-go/pull/295 ) is merged and released so closing out this issue.
