### ISSUE TITLE
Need a method for creating new segment from existing segment but not the same context

### ISSUE THREAD

**Issue by GnatorX** [aws/aws-xray-sdk-go#143]
We need a method to create new segments off of an existing one (pass trace id + parentId) without using the existing context. The reason is because we have an async app which responses prior to the completion of the async process. This causes the context to be completed which then breaks xray when the async process completes and it tries to get the segment back out from the context.

**Comment by luluzhao** [comment]
@GnatorX thank you for contacting us regarding your question. Based on your explanation, it seems like [NewSegmentFromHeader](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/segment.go#L210) works for the case. You can use trace id and parent id to construct a new xray header and then creating a new segment based on that.

**Comment by GnatorX** [comment]
Ah I see. Thanks
