### ISSUE TITLE
X-Ray logs are very noisy

### ISSUE THREAD

**Issue by johdah** [aws/aws-xray-sdk-go#147]
We use an external tool to collect all our logs in a single place and pay per log line. Currently in the following example every line is it's own log line even if the message is the same. [DEBUG] is nice because that makes it easy to filter out and don't forward debug messages in our log lambda. But since only the first line includes debug and the json isn't combined into a single line.

So is it possible to force a message like this into one row or at least add the DEBUG code (or something else) on every line so we can filter it out? If we pay for the log tool per line it's  bit frustrating when it's this wasteful.

````
2019-09-11T11:17:23Z [DEBUG] {
"trace_id": "1-5d78d7c3-b4a5fdac20289ff8c3daec1b",
"id": "dfb15b8325c40d57",
"name": "ourlambda",
"start_time": 1568200643.6972828,
"end_time": 1568200643.8107076,
"aws": {
"xray": {
"sdk_version": "1.0.0-rc.13",
"sdk": "X-Ray for Go"
}
},
"service": {
"compiler_version": "go1.12.1",
"compiler": "gc"
}
}
```

**Comment by luluzhao** [comment]
@johdah thank you for contacting us regarding your issue. Currently our Go SDK doesn't support print segment document into one line. We will add this into our backlog and in the meantime, a PR is welcome.
