### ISSUE TITLE
Aws Lambda Golang Error runtime

### ISSUE THREAD

**Issue by jeffotoni** [aws/aws-xray-sdk-go#153]
Hello people,

Suddenly the runtime error started ..
I'm using go1.13.4, but all other lambdas are ok.

Error:
"runtime error: invalid memory address or nil pointer dereference: errorString [{"path":"github.com/aws/aws-lambda-go@v1.13.3/lambda/function.go","line":35,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":679,"label":"gopan"

**Comment by willarmiros** [comment]
I think you might have meant to leave your issue here: https://github.com/aws/aws-lambda-go/issues

**Comment by jeffotoni** [comment]
Hi,
I found out what it was, the error was that I was trying to access an error without existing, with .Error ().

Thank you guys.
