### ISSUE TITLE
lambda handler not sending segments

### ISSUE THREAD

**Issue by thecaddy** [aws/aws-xray-sdk-go#155]
Hi there, 

I have spend hours trying to debug what is going on with the xray client, looking at the debug logs, all the segments and subsegments line up correctly but they never make it into xray.

I've tried `Close`, `CloseAndStream`, and `NewSegmentFromHeader`, they all fail to make it into xray.  I feel like there is something obvious I'm missing but I'm at a loss.  Additionally, udp send logs don't appear when deployed to lambda.

`data is obfuscated`

pkg versions:
```
	github.com/aws/aws-lambda-go v1.13.3
	github.com/aws/aws-sdk-go v1.25.41
	github.com/aws/aws-xray-sdk-go v1.0.0-rc.14
```

code: 
```
func lambdaHandler(context context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	xray.SetLogger(xraylog.NewDefaultLogger(os.Stdout, xraylog.LogLevelDebug))
	xray.Configure(xray.Config{})

	ctx, seg := xray.BeginSubsegment(context, "my-service")
        // do things
	seg.Close(nil)
}
```

logs: 
```
2019-11-24T19:25:57Z [DEBUG] using daemon endpoints from environment variable AWS_XRAY_DAEMON_ADDRESS: 169.254.79.2:2000
2019-11-24T19:25:57Z [DEBUG]{
  "trace_id": "1-5ddad944-b5da97845ad6cdb83d8ea004",
  "id": "7e203513d7caec83",
  "name": "my-service",
  "start_time": 1574623557.1645799,
  "end_time": 1574623557.234123,
  "parent_id": "5be0a36d79fea8e4",
  "type": "subsegment",
  "subsegments": [
    {
      "id": "17d24c896fdf7624",
      "name": "parse",
      "start_time": 1574623557.1646147,
      "end_time": 1574623557.1646545,
      "subsegments": [
        {
          "id": "74371d5adc9e6968",
          "name": "validation",
          "start_time": 1574623557.1646624,
          "end_time": 1574623557.1650312,
          "metadata": {
            "default": {
              "errors": null
            }
          }
        }
      ]
    }
  ]
}
```
xray raw:
```
{
  "Duration": 0.981,
  "Id": "1-5ddad944-b5da97845ad6cdb83d8ea004",
  "Segments": [
    {
      "Document": {
        "id": "0d3afd23531c54bb",
        "name": "my-service",
        "start_time": 1574623556.424,
        "end_time": 1574623557.237,
        "parent_id": "089f03c6b3fbca79",
        "http": {
          "response": {
            "status": 200
          }
        },
        "aws": {
          "request_id": "70716d1c-656a-43a4-9a44-31af34aa06ab"
        },
        "trace_id": "1-5ddad944-b5da97845ad6cdb83d8ea004",
        "origin": "AWS::Lambda",
        "resource_arn": "arn:aws:lambda:us-west-2:864984651651:function:my-service-stg-auth"
      },
      "Id": "0d3afd23531c54bb"
    },
    {
      "Document": {
        "id": "5be0a36d79fea8e4",
        "name": "my-service-stg-auth",
        "start_time": 1574623557.163,
        "end_time": 1574623557.235,
        "parent_id": "0d3afd23531c54bb",
        "aws": {
          "function_arn": "arn:aws:lambda:us-west-2:864984651651:function:my-service-stg-auth",
          "resource_names": [
            "my-service"
          ],
          "account_id": "864984651651"
        },
        "trace_id": "1-5ddad944-b5da97845ad6cdb83d8ea004",
        "origin": "AWS::Lambda::Function",
        "subsegments": [
          {
            "id": "6c51cb93680c34ea",
            "name": "Initialization",
            "start_time": 1574623556.697,
            "end_time": 1574623557.162,
            "aws": {
              "function_arn": "arn:aws:lambda:us-west-2:864984651651:function:my-service-stg-auth"
            }
          }
        ]
      },
      "Id": "5be0a36d79fea8e4"
    },
    {
      "Document": {
        "id": "7096104275b7dbc9",
        "name": "seller-source",
        "start_time": 1574623556.351,
        "end_time": 1574623557.332,
        "http": {
          "request": {
            "url": "http://my-service.com/",
            "method": "POST",
            "my_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0",
            "client_ip": "174.21.119.177",
            "x_forwarded_for": true
          },
          "response": {
            "status": 200
          }
        },
        "aws": {
          "xray": {
            "sdk": "X-Ray for Node.js",
            "sdk_version": "2.4.0",
            "package": "aws-xray-sdk"
          }
        },
        "service": {
          "version": "unknown",
          "runtime": "node",
          "runtime_version": "v10.17.0",
          "name": "unknown"
        },
        "trace_id": "1-5ddad944-b5da97845ad6cdb83d8ea004",
        "subsegments": [
          {
            "id": "089f03c6b3fbca79",
            "name": "https://fdsadfsd.execute-api.us-west-2.amazonaws.com",
            "start_time": 1574623556.353,
            "end_time": 1574623557.25,
            "http": {
              "request": {
                "url": "https://fdsadfsd.execute-api.us-west-2.amazonaws.com/",
                "method": "POST"
              },
              "response": {
                "status": 200
              }
            },
            "namespace": "remote"
          }
        ]
      },
      "Id": "7096104275b7dbc9"
    }
  ]
}
```

**Comment by bhautikpip** [comment]
Hi @thecaddy,

It looks like your configuration is correct. 

Follow up questions and suggestions from my side.

1. If you are not able to see traces on the xray console then where are you seeing raw trace data ?

2. It could be something with your aws cli configurations I would check that as a sanity check. Also I would check my lambda function policy. You have to attach AWSXrayWriteOnlyAccess Policy to your lambda function in order to send data to the xray console. One important thing to note is you need to start Active xray tracing on lambda console.

Hope this helps!

**Comment by thecaddy** [comment]
Thanks for getting back to me, the raw xray is coming directly from xray.

1. The log shows the data is being sent to xray, so I see the trace id and the subsegment id's. 

2. Xray shows the trace of the execution lambda but nothing internal to the execution.  You can see I send the subsegments but they don't appear in xray and I am stumped as to why.  I use the node equivalent xray client and the traces come through fine.

Are these the correct permissions?

```
          {
            "Action": [
              "xray:PutTraceSegments",
              "xray:PutTelemetryRecords"
            ],
            "Resource": [
              "*"
            ],
```

**Comment by bhautikpip** [comment]
Hi @thecaddy,

Interesting. Do you see any kind of errors in the logs ? because it looks like data is being sent to xray. I am talking about the lambda function execution role you have to attach AWSXrayWriteOnlyAccess this policy to your lambda function execution role and enable xray tracing on lambda console. Do you see initialization subsegment on the xray console ?

**Comment by thecaddy** [comment]
I don't see any errors in the logs.  I have debug log level on and what i have above is the most it gives me.  I agree everything looks like its behaving correctly which is why I came here as a last result.  I don't see any way to get logging of the request/response sent to the xray daemon that is supposed to be setup for lambda?  This is a mysterious black box so not sure if the issue may be there.

I use cloud formation to setup the lambdas and I believe it is enabled.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/1521981/70807056-88b08080-1d71-11ea-807c-0c729f386fb4.png">


As for the logs, I see two important logs, I see one for each subsegment created/closed and I see a final log, the one i pasted above of the nested comprehensive series of subsegments.
