### ISSUE TITLE
Use of reflection probably cause performance issues on method segment.AddAnnotation

### ISSUE THREAD

**Issue by michelaquino** [aws/aws-xray-sdk-go#168]
Is this check of annotation value type really necessary?
https://github.com/aws/aws-xray-sdk-go/blob/master/xray/segment.go#L422-L426

The use of reflection could cause performance issues when this is used with high demand.
Make sense?

**Comment by bhautikpip** [comment]
Hi @michelaquino,

As per my understanding that check of annotation is necessary. Can you suggest any other better ways to re write this logic without use of reflection ?

**Comment by michelaquino** [comment]
The easy way to do this is create different methods to specific parameters type. Is this possible?

**Comment by bhautikpip** [comment]
Hi @michelaquino,

It is possible since we are checking the value type. We really appreciate PR!
