### ISSUE TITLE
Getting "segment cannot be found" when using xray.Client

### ISSUE THREAD

**Issue by ivancevich** [aws/aws-xray-sdk-go#18]
Hi there,
I'm trying to use `xray.Client` instead of `http.DefaultClient` for calling 3rd party services. I'm getting an error such as `panic: failed to begin subsegment named 'api.github.com': segment cannot be found.` when doing so.
Am I doing something wrong?
Thank you in advance!

**Comment by luluzhao** [comment]
@ivancevich, the error message means there is no segment found when trying to create subsegment for it. Are you only using xray.Client API? You can manually create a segment by using xray.BeginSegment and pass corresponding returned ctx to ctxhttp.Get(ctx, xray.Client(nil), "https://aws.amazon.com/") like the example in README. Tell me if it's worked or not. If not, please tell me more how you implemented xray to your app. Thank you.

**Comment by ivancevich** [comment]
@luluzhao I'm trying to set the `xray.Client` to be used by other libraries, such as this Facebook client github.com/huandu/facebook.
I'm doing something like this: `facebook.SetHttpClient(xray.Client(nil))`. But now that I know it requires a context, I'm not sure if this could work.

**Comment by vincent6767** [comment]
Any update here?

**Comment by tmaiaroto** [comment]
Not working for me either. I've tried about a dozen different ways following the README. Trying to set the RoundTripper for accessing S3 using Minio. https://docs.minio.io/docs/golang-client-api-reference#SetCustomTransport

**Comment by luluzhao** [comment]
@ivancevich , I looked at this library `github.com/huandu/facebook`. There is a section at the end of `README` named `Control timeout and cancelation with Context`. By passing a context which contains a segment in your method, a subsegment will be generated automatically.

**Comment by luluzhao** [comment]
@tmaiaroto , thank you for reaching out to us. Could you tell me more details about your implementation? Like I said in my first comment, have you provide a context which contains a segment and a xray client into your method?

**Comment by itmeze** [comment]
I am having similar issue. Such an example: 
```go
package main

import (
	"context"
	"github.com/aws/aws-xray-sdk-go/xray"
	"golang.org/x/net/context/ctxhttp"
)

func main() {
	ctx, seg := xray.BeginSegment(context.Background(), "just-a-test")
	_, err := ctxhttp.Get(ctx, xray.Client(nil), "https://aws.amazon.com/")
	if err != nil {
		seg.AddError(err)
	}
	seg.Close(nil)
}
```
panics with 'failed to begin subsegment named 'aws.amazon.com': segment cannot be found.'

**Comment by itmeze** [comment]
Okay, in my case updating "golang.org/x/net/context/ctxhttp" seems to resolve problem.
```
go get -u golang.org/x/net
```
I hope that helps others...

**Comment by luluzhao** [comment]
@itmeze , thank you for updating this thread. Could you tell me which version of `golang.org/x/net/context/ctxhttp` that was not working?

**Comment by itmeze** [comment]
@luluzhao i was using rev c4c3ea71919de159c9e246d7be66deb7f0a39a58
As you can see, at the time there was no request.Context() so obviously this would fail https://github.com/golang/net/blob/c4c3ea71919de159c9e246d7be66deb7f0a39a58/context/ctxhttp/ctxhttp.go#L49

**Comment by tobowers** [comment]
so how do we work with libraries that don't automatically use the WithContext methods?

**Comment by luluzhao** [comment]
@tobowers , we inject segment information into context to keep track of customer's application activities. In order to use our Go SDK properly, it has to use WithContext methods.

**Comment by kaihendry** [comment]
Hi, has anyone got a simple worked example to share?

https://media.dev.unee-t.com/2019-04-24/aws-sam-xray-go.mp4

The `sam init --runtime go1.x` boilerplate don't appear to expose context. :thinking:

**Comment by tdhulster** [comment]
Any updates on this? 
> so how do we work with libraries that don't automatically use the WithContext methods?

This simple construct does not seem to work : 
`
xrayHttpClient := xray.Client(nil)
xrayHttpClient.Do()
`

And throws errors like : 
[ERROR] Suppressing AWS X-Ray context missing panic: failed to begin subsegment named 'api.mollie.com': segment cannot be found. | 2020-12-15T16:33:51Z [ERROR] Suppressing AWS X-Ray context missing panic: failed to begin subsegment named 'api.test': segment cannot be found.

Even when beginning a segment right before does not seem to help. 
`
xray.BeginSegment(context.Background(), "test")
xrayHttpClient := xray.Client(nil)
xrayHttpClient.Do()
`
