### ISSUE TITLE
SQL Usage

### ISSUE THREAD

**Issue by DaveBlooman** [aws/aws-xray-sdk-go#19]
The SQL wrapper is really great, especially when used with a normal web app.  When you are doing a job that is not based on a http request, the usage becomes a little more complex.

The readme is slightly incorrect, it should have a context object passed into the query. 

```go
func main() {
  db := xray.SQL("postgres", "postgres://user:password@host:port/db")
  row, _ := db.QueryRow(ctx, "SELECT 1") // Use as normal
}
```

This calls capture, which is a new subsegment, but that assumes you have an existing segment.  It will panic.

I found this when doing testing, that often you wont be using the xray handler wrapper, so the context will not be created.  Could we change the approach to check for the existence of a segment and create one if there isn't one present?

**Comment by luluzhao** [comment]
@DaveBlooman , thank you for pointing out the incorrect readme session and we gonna fix it by next release. For SQL methods, we don't support create one if no segment present for now. Customer needs to create a segment or using Handler function to create one and pass the context to SQL method. If we support "create one if not present" case, it gonna be some problems i,e, what we gonna name the segment?. What's more, it may mess up when propagate to other methods. Maybe in the future we can add one feature in ContextMissingStrategy to support "create one if not present", however, customer needs to provide a segment for using SQL methods so far.

**Comment by ansyser** [comment]
```
func main() {
  db := xray.SQL("postgres", "postgres://user:password@host:port/db")
  row, _ := db.QueryRow("SELECT 1") // Use as normal
}
```  
The readme session is still incorrect
