### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by martin-flower** [aws/aws-xray-sdk-go#192]
We have received complaints that our service is writing too much to the logs. Notably, can the service please stop logging : 
`using daemon endpoints from environment variable AWS_XRAY_DAEMON_ADDRESS`
`Emitter using address`
which come from `aws-xray-sdk-go`

How is it possible to stop these?

**Comment by shogo82148** [comment]
Its log level is `LogLevelInfo`, so set the log level lower than `LogLevelInfo`.

```go
xray.SetLogger(xraylog.NewDefaultLogger(os.Stderr, xraylog.LogLevelWarn))
// or xray.SetLogger(xraylog.NewDefaultLogger(os.Stderr, xraylog.LogLevelError))
```

**Comment by bhautikpip** [comment]
Also, you can use logger section in README.MD (https://github.com/aws/aws-xray-sdk-go) to get more information about how X-RAY Go SDK implements logger.

**Comment by martin-flower** [comment]
If I understand this correctly, if we set the log level to `Warn`, then we will lose the `Info` logging in our service?

In order to log at `Info` in our service, but not log `Info` in aws-xray-sdk-go, do we have to add logic to a custom logger?

**Comment by bhautikpip** [comment]
Hi @martin-flower,

I believe if you set log level to `Warn` then you will not lose `Info` logging in your service. I think it will emit x-ray specific logging information and not your service specific. I have assumed you are not using X-Ray's default logger implementation in your service.

**Comment by martin-flower** [comment]
Thanks for all the comments - I'll need to spend more time understanding custom logging, but meanwhile I'll set the level to Warn. This is the current code which I'm working with:

```
_ = xray.Configure(xray.Config{})
xray.SetLogger(utils.NewDefaultLogger(os.Stderr, xraylog.LogLevelWarn))

```

**Comment by bhautikpip** [comment]
Looks great! I am closing this issue for now feel free to reopen this if you still see any issue.
