### ISSUE TITLE
Track SQS in goroutine

### ISSUE THREAD

**Issue by sunao-uehara** [aws/aws-xray-sdk-go#203]
I am using xray to trace SQS in http handlers. It works fine when it runs synchronously. But when I use goroutine to run it asychronously, I get context Cancellation error because http request is done and context is canceled before finish sending sqs message.

Then I tried using xray.NewSegmentFromHeader() to create new context based on parent segment's header. but still I am getting same error, I thought return context from NewSegmentFromHeader() is newly created context and so it won't be canceled. But it seems not?
Anyone having same issue or am I doing something wrong?

```
func TestHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	s := xray.GetSegment(ctx)
	xrayHeader := s.DownstreamHeader()
	newCtx, _ := xray.NewSegmentFromHeader(ctx, "AsyncTask", r, xrayHeader)

        xray.AWS(sqsClient)
	go func() {
	     input.QueueUrl = "****"
	     input.DelaySeconds = 1
	    _, err = sqsClient.SendMessageWithContext(newCtx, input)
	}()
}
```

I also tried using xray.CaptureAsync(), but still getting same error.
```
func TestHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	s := xray.GetSegment(ctx)
	xrayHeader := s.DownstreamHeader()
	newCtx, _ := xray.NewSegmentFromHeader(ctx, "AsyncTask", r, xrayHeader)

        xray.AWS(sqsClient)
        xray.CaptureAsync(newCtx, "PostWorkerTaskAsync", func(ctx1 context.Context) error {
	    go func() {
	         input.QueueUrl = "****"
	         input.DelaySeconds = 1
	        _, err = sqsClient.SendMessageWithContext(ctx, input)
	    }()
            return nil
        })
}
```

<img width="1191" alt="Screen Shot 2020-03-10 at 6 01 10 PM" src="https://user-images.githubusercontent.com/2450585/76372861-0269f300-62fc-11ea-9fd8-9fd70a3141ec.png">

<img width="955" alt="Screen Shot 2020-03-10 at 6 01 21 PM" src="https://user-images.githubusercontent.com/2450585/76372864-07c73d80-62fc-11ea-9021-79bd0ae0bb93.png">

**Comment by bhautikpip** [comment]
Hi @sunao-uehara,

I think it looks like main goroutine completes its execution before the goroutine you have created. Since you are passing newCtx to spawned goroutine because of the main goroutine has executed there's no context. I think you should use go channels or waitgroups to address this issue so that main goroutine waits for other goroutines to execute and then execute the program.

**Comment by sunao-uehara** [comment]
Hi @bhautikpip ,

Thank you for quick response and suggestion, so conclusion is that I just need to wait `go func()` finishes like following code in order to keep context alive, right? So there is no way to let it run without waiting? The reason is that, in real code, I have heavy sql queries before sending sqs, so I don't want to wait it finishes and return http response to caller as soon as possible.

```
       xray.AWS(sqsClient)
       var wg sync.WaitGroup
       wg.Add(1) 
       go func() {
	     input.QueueUrl = "****"
	     input.DelaySeconds = 1
	    _, err = sqsClient.SendMessageWithContext(newCtx, input)
            wg.Done()
       }()
       wg.Wait()
```

**Comment by bhautikpip** [comment]
Hi @sunao-uehara,

I think it depends on how you want to trace SQSSendMessage call. For example if you want to trace you heavy sql query and SQS call in one segment then you will have to pass the context and wait and if you want to create another segment for SQS call then you don't have to pass the context in the goroutine. Hope this makes sense!

**Comment by sunao-uehara** [comment]
Hi @bhautikpip 

I think I didn't explain properly, the heavy sql queries is in `go func()` right before `sqsClient.SendMessageWithContext(newCtx, input)`, so I don't want wait it and just return http response immediately.  I don't mind separating segment for SQS sendMessage and  segment for incoming request trace of `TestHandler`. Actually I thought that's only way to trace sqs in goroutine since context for `TestHandler` would be canceled. That's why I tried `xray.NewSegmentFromHeader()` to try creating new segment and context ,and use them for sqs. but it didn't work, I got `context canceled` error. So I am confused about the use-case of `xray.NewSegmentFromHeader()`

By the way I found and tried this `DetachContext()` just for detaching current context and use new context to avoid context canceled issue.
https://github.com/aws/aws-xray-sdk-go/blob/master/xray/context.go#L70-L75
```
// DetachContext returns a new context with the existing segment.
// This is useful for creating background tasks which won't be cancelled
// when a request completes.
func DetachContext(ctx context.Context) context.Context {
	return context.WithValue(context.Background(), ContextKey, GetSegment(ctx))
}
```

Here is code
```
func TestHandler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	newCtx := xray.DetachContext(ctx)
        xray.AWS(sqsClient)
	go func() {
	     input.QueueUrl = "****"
	     input.DelaySeconds = 1
	    _, err = sqsClient.SendMessageWithContext(newCtx, input)
	}()
}
```

It works!  And even the sqs tracing is showing up as sub segment.

<img width="978" alt="Screen Shot 2020-03-11 at 5 11 04 PM" src="https://user-images.githubusercontent.com/2450585/76475278-9353d380-63bb-11ea-89a6-278115bbf6fe.png">
<img width="1182" alt="Screen Shot 2020-03-11 at 5 10 57 PM" src="https://user-images.githubusercontent.com/2450585/76475284-96e75a80-63bb-11ea-804c-ef2c1a10dba2.png">

But I am not sure if this is ideal way to use `DetachContext()`. Could you give me advice?

**Comment by bhautikpip** [comment]
Hi @sunao-uehara,

I think xray.NewSegmentFromHeader() is designed to use internally. When we receive any upstream call handler will call this API and then internally this API will call xray.BeginSegment API. BeginSegment basically creates a segment for any upstream call to clear out the confusion about xray.NewSegmentFromHeader. Moreover, DetachContext() is more useful in the case of background tasks. It looks like you are doing something similar to that so I would say using DetachContext() makes more sense. Let me know if you have further questions or issues.

**Comment by sunao-uehara** [comment]
Hi @bhautikpip,

Thanks for explanation for NewSegmentFromHeader(), so I would use DetachContext() for background job for now.
