### ISSUE TITLE
xray.SQL unable to handle db.SQL query string - fails with "sql: converting argument $1 type: unsupported type []interface {}, a slice of interface"

### ISSUE THREAD

**Issue by mlindes** [aws/aws-xray-sdk-go#204]
A query to an Azure mssql db began to fail with recent build of an app. 
Running the query with `database/sql` library works well like:
```
GenQuery := "select ..."
db, err = sql.Open("sqlserver", connString)
rows, err := db.Query(ctx, GenQuery)
...
```
Modifying to use with the db open to use the xray library with:
```
GenQuery := "select ..."
db, err := xray.SQL("sqlserver", connString)
rows, err := db.Query(ctx, GenQuery)
```
Running through SAM, returns the error:
```
{"errorType":"errorString","errorMessage":"sql: converting argument $1 type: unsupported type []interface {}, a slice of interface"}
```
Similarly, running the lambda in AWS logs this to cloudwatch:
```
sql: converting argument $1 type: unsupported type []interface 
{}
, a slice of interface: errorString
null
```
Based on timing, this appears to be related to [pr169](https://github.com/aws/aws-xray-sdk-go/pull/169) as tracing was working well up til a recent built. Following-up now to try to get it working again, I've found this recent large update. 

The query I'm passing in is a simple standard query on a single table passed as a string variable. 
Attempted modifying the where claues to use `args...` where possible, but the error persists.

**Comment by bhautikpip** [comment]
Hi @mlindes,

which driver are you using ? I think it looks like you are missing args here. It should be something similar to like this. 
`rows, err := db.Query(ctx, GenQuery, 1)`

I tried the below example with MySQL database and was able to trace the query.

```
ctx, root := xray.BeginSegment(context.Background(), "segment name")
db, _ := xray.SQL("mysql", "root:password@tcp(127.0.0.1:3306)/testdb")
db.QueryContext(ctx, "SELECT bar FROM foo WHERE bar = ?",1)
root.Close(nil)
```

**Comment by shogo82148** [comment]
my note:

> "sql: converting argument $1 type: unsupported type []interface {}, a slice of interface"

This message is here.

https://github.com/golang/go/blob/fae87a2223e1fa959a20017742455200fe3c35f1/src/database/sql/convert.go#L194

**Comment by mlindes** [comment]
Hi @bhautikpip .. sorry I didn't include my libraries..
```
	"github.com/aws/aws-xray-sdk-go/xray"
	_ "github.com/denisenkom/go-mssqldb"
```

The Query I'm working with only has one argument, and it's a string, so I set it ahead of time. 
That said, I've broken it out & passing it in with `args` like
```
myStringVariable := "TheThingIWant"
GenQuery := "select col1,col2 from table where col1 = '$1'"
db, err = sql.Open("sqlserver", connString)
rows, err := db.Query(ctx, GenQuery, myStringVariable)
```

...I've tried several iterations of this, using backticks backticks, string converstions, limiting the query. I get the same error every time. I'd like to be able to force-disable the `ColumnConverter`

**Comment by mlindes** [comment]
Also worth noting... the [aws-xray-sdk-go](https://github.com/aws/aws-xray-sdk-go) README states:
> Note that the xray.SQL are deprecated and will be remove when the SDK becomes GA.
..I've been unable to compile with `xray.SQLContext` .. I'm on `go1.13.4 linux/amd64`

**Comment by bhautikpip** [comment]
> Also worth noting... the [aws-xray-sdk-go](https://github.com/aws/aws-xray-sdk-go) README states:
> 
> > Note that the xray.SQL are deprecated and will be remove when the SDK becomes GA.
> 
> ..I've been unable to compile with `xray.SQLContext` .. I'm on `go1.13.4 linux/amd64`

I have released XRay Go SDK v1.0.0-rc.15 just now and it includes xray.SQLContext API. so now if you update the SDK you should be able to compile it.

**Comment by mlindes** [comment]
This looks promising. It compiled, ran in SAM, deployed and now getting trace data visible in xray.
Don't see the db call in the service map yet, but the lambda runs only once every 20 mins per region. 
I'll instrument a subsegment to help see what I want to see... 

Thanks for the quick replies on this!

**Comment by mlindes** [comment]
Just to include some fuller details for anyone looking...  

```
import (
	"github.com/aws/aws-xray-sdk-go/xray"
	_ "github.com/denisenkom/go-mssqldb"
)

connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d;database=%s;",
	Secrets.Host,
	Secrets.Username,
	Secrets.Password,
	Secrets.Port,
	Secrets.Dbname,
)

myStringVariable := "theThingIWant"
genQuery := "select col1,col2 from table where col1=" + theThingIWant + " and col2='xxx';"

xdb, err := xray.SQLContext("sqlserver", connString)
rows, err := xdb.QueryContext(ctx, genQuery)
```

**Comment by bhautikpip** [comment]
Thanks for sharing this!

**Comment by mlindes** [comment]
@bhautikpip - just some follow-up fyi. 
With the new rc, my linter complains about  two undefined vars: `emitter` and `streamingStrategy` 
from [xray/config.go globalConfig](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L100-L110) 

Otherwise, tracing is working as expected. Thanks again!.

**Comment by bhautikpip** [comment]
Hi @mlindes,

can you post the warning msg ?

**Comment by mlindes** [comment]
```
# github.com/aws/aws-xray-sdk-go/xray
../../../github.com/aws/aws-xray-sdk-go/xray/config.go:104:30: undefined: Emitter
../../../github.com/aws/aws-xray-sdk-go/xray/config.go:107:30: undefined: StreamingStrategy
Process exiting with code: 2
```

**Comment by bhautikpip** [comment]
Hi @mlindes,

I checked linter logs couldn't see this undefined warnings on my end.
