### ISSUE TITLE
Wrapping Aws-xray with gorilla mux

### ISSUE THREAD

**Issue by continuum-ajay-sahani** [aws/aws-xray-sdk-go#246]
Hi,
We have used gorilla mux (https://github.com/gorilla/mux) in our codebase as following:

router := mux.NewRouter().StrictSlash(true)
api := router.PathPrefix("/routes").Subrouter()
api.Handle("/version", WrapMethodHandler(http.MethodGet, rest.HandlerVersion))

type MethodHandler map[string]http.Handler
func WrapMethodHandler(method string, fn func(w http.ResponseWriter, _ *http.Request)) MethodHandler {
	return MethodHandler{
		method: http.HandlerFunc(fn),
	}
}

Please help us, to wrap this handler inside xray as https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-handler.html

**Comment by bhautikpip** [comment]
Hi @continuum-ajay-sahani ,

You should be able to trace upstream HTTP call using something like this.

```
router := mux.NewRouter()
router.Handle("/", xray.Handler(xray.NewFixedSegmentNamer("newsegment"), HelloServer()))
```

In above example HelloServer() method is a function handler. So add any function handler method in place of 
HelloServer() method. 

Let me know if you have more questions.

**Comment by continuum-ajay-sahani** [comment]
In this code snippet, how to mention HTTP method type (GET, POST,etc) for the handler ?

**Comment by bhautikpip** [comment]
I believe you should be able to mention it in the http handler code. In the above example HelloServer() is the http handler. Whenever this path ('/') is being hit it will call the http handler and perform operations like GET, POST etc. I believe you can review the example in this thread (https://github.com/aws/aws-xray-sdk-go/issues/238) to get more clear idea.
