### ISSUE TITLE
AWS recoder for Golang

### ISSUE THREAD

**Issue by continuum-ajay-sahani** [aws/aws-xray-sdk-go#248]
Hi AWS Team,
We are integrating AwsXray in our product which is written in Go, to do that we need to do code changes in our application, do we have any recorder(agent) so that we do not need to do changes in our codebase just like we have for Java and .Net application (Recoder).

**Comment by bhautikpip** [comment]
Hi @continuum-ajay-sahani ,

Currently, we don't have an agent for Golang like we have in Java and .NET .
