### ISSUE TITLE
Use of custom header parsing and creating in xray/handler.go instead of using header.Header 

### ISSUE THREAD

**Issue by fabianfett** [aws/aws-xray-sdk-go#25]
Hi,

I am relatively new to GO, coming from Node.js. Currently I'm trying to implement xray tracing for grpc (building client and server interceptors). Therefore I had a deep look into the http handler. As I said I am new to GO so I may be completely lost but this looks fishy to me:

```go
		trace := parseHeaders(r.Header)
		if trace["Root"] != "" {
			seg.TraceID = trace["Root"]
			seg.RequestWasTraced = true
		}
		if trace["Parent"] != "" {
			seg.ParentID = trace["Parent"]
		}
		// Don't use the segment's header here as we only want to
		// send back the root and possibly sampled values.
		var respHeader bytes.Buffer
		respHeader.WriteString("Root=")
		respHeader.WriteString(seg.TraceID)
		switch trace["Sampled"] {
		case "0":
			seg.Sampled = false
			log.Trace("Incoming header decided: Sampled=false")
		case "1":
			seg.Sampled = true
			log.Trace("Incoming header decided: Sampled=true")
		default:
			seg.Sampled = privateCfg.SamplingStrategy().ShouldTrace(r.Host, r.URL.String(), r.Method)
			log.Tracef("SamplingStrategy decided: %t", seg.Sampled)
		}
		if trace["Sampled"] == "?" {
			respHeader.WriteString(";Sampled=")
			respHeader.WriteString(strconv.Itoa(btoi(seg.Sampled)))
		}
		w.Header().Set("x-amzn-trace-id", respHeader.String())
```

```go
func parseHeaders(h http.Header) map[string]string {
	m := map[string]string{}
	s := h.Get("x-amzn-trace-id")
	for _, c := range strings.Split(s, ";") {
		p := strings.SplitN(c, "=", 2)
		k := strings.TrimSpace(p[0])
		v := ""
		if len(p) > 1 {
			v = strings.TrimSpace(p[1])
		}
		m[k] = v
	}
	return m
}
```

Why is there a custom parsing method for the Header? There already is a header package with a `header.Header` that can be constructed with a string. This one is even used right at the top `traceHeader := header.FromString(r.Header.Get("x-amzn-trace-id"))` 

Also the response header can be constructed with the Header object.

If I can help with a pr I am more than happy to do so.

Regards from Germany,
  Fabian

**Comment by fabianfett** [comment]
Digging deeper; The method call `NewSegmentFromHeader` already takes care of quite an amount of the current code. But `seg.RequestWasTraced = true` is missing? Does this need to be added?

```go
// NewSegmentFromHeader creates a segment for downstream call and add information to the segment that gets from HTTP header.
func NewSegmentFromHeader(ctx context.Context, name string, h *header.Header) (context.Context, *Segment) {
	con, seg := BeginSegment(ctx, name)

	if h.TraceID != "" {
		seg.TraceID = h.TraceID
	}
	if h.ParentID != "" {
		seg.ParentID = h.ParentID
	}
	seg.Sampled = h.SamplingDecision == header.Sampled
	seg.IncomingHeader = h

	return con, seg
}
```

**Comment by luluzhao** [comment]
@fabianfett , thank you for pointing this out to us. We will start working on refactoring our code and there will be no functional behavior change of SDK.

**Comment by luluzhao** [comment]
@fabianfett Thank you for your suggestions and we just release a new version `v1.0.0-rc.3` which refactors code to prevent repetition. Feel free to pull our new version.
