### ISSUE TITLE
Add silent error option for AWS_XRAY_CONTEXT_MISSING 

### ISSUE THREAD

**Issue by mikeparker** [aws/aws-xray-sdk-go#251]
Right now we use xray in a shared library, invisible to the consumer. Sometimes the methods are called outside of an Xray segment, for example for a long running container that might sit for days receiving messages, but uses some AWS calls (e.g. SSM) on boot, which will be outside of the trace.

Right now we have 2 options using AWS_XRAY_CONTEXT_MISSING:
1. Runtime error
2. Spam the log file

Ideally, we want a 3rd option: silently ignore it.

**Comment by bhautikpip** [comment]
I think this is a fair ask. I am going to work on this and hopefully will have a pull request out soon.

**Comment by bhautikpip** [comment]
Hi @mikeparker ,

I submitted a pull request to address this. (https://github.com/aws/aws-xray-sdk-go/pull/253). Can you confirm if this will solve your issue ?

**Comment by bhautikpip** [comment]
released in X-Ray go SDK v1.2.0 so resolving. [Change-log](https://github.com/aws/aws-xray-sdk-go/blob/master/CHANGELOG.md) for details.
