### ISSUE TITLE
No way to access the current Config

### ISSUE THREAD

**Issue by fabianfett** [aws/aws-xray-sdk-go#26]
As far as I can see there is currently no way to access the current `Config` object. `privateCfg` is of course `private` and `Configure(c Config)` sets the private state. But there is no way to read the config. This is needed for implementing custom incoming handlers in which we need decide the sampling strategy based on `samplingStrategy sampling.Strategy`.

Thanks so much for your help and consideration,
  Fabian

**Comment by rvdwijngaard** [comment]
any update on this?

**Comment by luluzhao** [comment]
@rvdwijngaard , thank you for reaching out to us. Currently this code change is under code review and it will be released when X-Ray Go SDK goes GA.
