### ISSUE TITLE
No in_progress flag generated when using the aws-xray-sdk-go to emit trace data

### ISSUE THREAD

**Issue by JohnWu20** [aws/aws-xray-sdk-go#262]
From this [doc](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-subsegments) the in_progress is a required flag. However, when I use go sdk to emit the trace data, there is not in_progress flag when it's false. This may be a bug for go sdk.

**Comment by bhautikpip** [comment]
I think Go SDK scrap out the `in_progress` flag if `end_time` value is set and looks like this is expected behavior so I won't consider it as a bug.
