### ISSUE TITLE
Can't run Github Actions due to deprecated set-env syntax

### ISSUE THREAD

**Issue by sawadashota** [aws/aws-xray-sdk-go#265]
I created PR #264 but all Github Actions jobs went fail because this project uses deprecated set-env syntax.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by bhautikpip** [comment]
Sure. Thanks for creating an issue. I will submit a PR to address test case failures.
