### ISSUE TITLE
What's the official way of tracing messages in sqs

### ISSUE THREAD

**Issue by fabianfett** [aws/aws-xray-sdk-go#27]
Hi,

is there an official way that we should use to trace messages that are processed asynchronously in sqs? For example: 

1.) request comes in triggers a task in sqs
2.) worker service get's message from sqs and processes the message.

My simple solution would be to build some kind of sender, that wraps the sqs functionality and attaches a tracing header to every sqs message in the MessageAttributes. The MessageAttributes header could then be unpacked in the message processor.

Of course, since we do have the context in 

```go
  queue.SendMessageWithContext(ctx, &sqs.SendMessageInput{
    MessageBody: aws.String("This is a test"),
    QueueUrl: aws.String("https://sqs.eu-central-1.amazonaws.com/***/some-queue"),
  })
```

the sdk could add the MessageAttribute automatically? Is this something that will happen at any time in the future?

This future would also be awesome for the SNS publish action. ;)

Thanks so much for your time and consideration,
  Fabian

**Comment by luluzhao** [comment]
@fabianfett , thank you for reaching out to us about your ideas. Currently we are working on this feature in Java SDK and probably is going to release it soon. In our implementation, we will attach a tracing header into every sqs message's attribute like you mentioned above. After we release the feature for SQS, we may start thinking about implement similar thing in SNS.

**Comment by kamoljan** [comment]
@luluzhao it is already implemented?
