### ISSUE TITLE
aws Iam assumeRole and Get Temp credentials using boto3 doesn't return Services in get_service_graph for xray

### ISSUE THREAD

**Issue by sumit2k21** [aws/aws-xray-sdk-go#302]
```
    def assume_role(self,account_id, role_name, duration, external_id):
        role_arn = "arn:aws:iam::" + account_id + ":role/" + role_name
        role_session_name = "AssumeRoleSession"
        client = boto3.client('sts', 'us-east-2')
        response = client.assume_role(RoleArn=role_arn,
                RoleSessionName=role_session_name,
                DurationSeconds=duration,
                ExternalId=external_id
                )
        tmp_credentials = {
                'access-key-id': response['Credentials']['AccessKeyId'],
                'secret-access-key': response['Credentials']['SecretAccessKey'],
                'session-token':response['Credentials']['SessionToken']
                }
        return tmp_credentials
    def create_clients(self, account_credentials):
        account_id = account.get('account-id')
        role_name = account.get('role-name')
        duration = 3600
        external_id = account.get('external-id')
        region_name= account.get('region-name')
        tmp_credentials = self.assume_role(account_id,role_name,duration,external_id)
        xray_client = boto3.client('xray',
                                      aws_access_key_id=tmp_credentials.get('access-key-id'),
                                      aws_secret_access_key=tmp_credentials.get('secret-access-key'),
                                      aws_session_token=tmp_credentials.get('session-token'),
                                      region_name=region_name)
```

Now I do: 

```
    response = xray_client.get_service_graph(StartTime=start_time, 
                                                        EndTime=end_time)    
    print(f"response: {response}")
```

The response I get is not proper, It is 

`    response: {'ResponseMetadata': {'RequestId': '0fa2d89c-4adf-4816-b86e-240cff3fdad6', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 15 May 2021 12:54:50 GMT', 'content-type': 'application/json', 'content-length': '97', 'connection': 'keep-alive', 'x-amzn-requestid': '0fa2d89c-4adf-4816-b86e-240cff3fdad6'}, 'RetryAttempts': 0}, 'Services': [], 'ContainsOldGroupVersions': False}
`
See the Services value in the response is an empty list [], That is the problem. If I access xray directly using the account permanent access_key_id and secret_key_id instead of tmp_credentials (id,id,sessionToken), I get multiple services in the Services list.
references I have followed are: 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/xray.html#XRay.Client.get_service_graph

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

Also the Role is configured properly in the target AWS account with awsXrayFullAccess policy and multiple other policies as well.

**Comment by willarmiros** [comment]
Hi @sumit2k21,

This repo is for issues related specifically to the X-Ray *instrumentation* SDK for Golang, whereas your issue is with using the X-Ray client of the AWS SDK. I would recommend opening this issue in the [AWS SDK for Python repo](https://github.com/boto/boto3/issues) as it is out of scope for this repo.
