### ISSUE TITLE
Missing service detail when instrumenting AWS SDK v2

### ISSUE THREAD

**Issue by kevinmcconnell** [aws/aws-xray-sdk-go#320]
Hi :wave: I'm trying to instrument code that uses V2 of the AWS SDK, using the support added in #277.  When using `awsv2.AWSV2Instrumentor` per the example in the README, I see the calls to services in the my traces, but there is none of the detail that is captured when using the V1 SDK.

For example, here is a trace using V2.  I can see there was an `UpdateItem` call which took 774ms, but there is no information captured about _why_ it took that long.

<img width="1181" alt="Screenshot 2021-07-21 at 11 52 00" src="https://user-images.githubusercontent.com/1186763/126478449-0b9bcb91-d786-42ad-860f-af276441ba8f.png">

Whereas, a trace using `xray.AWS()` on the V1 SDK looks like the following.  I can see the table name, see that the bulk of the time was spent on the TLS handshake, see that there were no retries needed, etc.

<img width="1074" alt="Screenshot 2021-07-21 at 11 51 01" src="https://user-images.githubusercontent.com/1186763/126478465-033f686d-eda9-4c2b-b5fe-d4b5358f9a45.png">

Is this expected behaviour, and a current limitation of the V2 SDK instrumentation?  Or should I be able to capture the detail of the service trace when using V2?

Thanks!

**Comment by bhautikpip** [comment]
Yes, I think with current V2 instrumentation you won't be able to capture all the calls details as captured in V1. I think this is the expected behavior and how V2 instrumentation works.

**Comment by kevinmcconnell** [comment]
Thanks, @bhautikpip, for the confirmation 👍

I'll close this issue then, since it's working as expected.

**Comment by vishen** [comment]
Apologies for commenting on a closed issue, and let me know if I should open another issue instead. But I was wondering if we will ever get the same xray trace in V2 that we got in V1, or if this just won't ever be possible?  It is currently a blocker for us moving to `aws-sdk-go-v2` and just wanted to know if it will be addressed eventually or if it isn't even possible.

**Comment by willarmiros** [comment]
Hi @vishen,

This is unfortunately a limitation at the AWS SDK go v2 level and not something we can control.

**Comment by vishen** [comment]
@willarmiros No worries, thanks for the response :)

**Comment by farazoman** [comment]
for anyone looking for table_name field info, I've made a separate issue in that case https://github.com/aws/aws-xray-sdk-go/issues/497
