### ISSUE TITLE
data race in concurrent calls to BeginSubsegment

### ISSUE THREAD

**Issue by elan-sg** [aws/aws-xray-sdk-go#35]
I think https://github.com/aws/aws-xray-sdk-go/blob/master/xray/segment.go#L183-L184 need to go inside the locks?

**Comment by luluzhao** [comment]
@elan-sg , thank you for reaching out to us. Yes, these two lines may cause a potential data rate. I will fix this one in our next release. Thank you.

**Comment by raymolin** [comment]
For visibility, similar issue here https://github.com/aws/aws-xray-sdk-go/blob/master/xray/segment.go#L70-L80.

When a context gets cancelled, there is a data race between the Close method and the snippet linked.

**Comment by luluzhao** [comment]
@elan-sg @raymolin We released a new version `v1.0.0-rc.3` to fix the data race condition. Thank you for your suggestions.
