### ISSUE TITLE
error on aws codestar build of aws-xray

### ISSUE THREAD

**Issue by sunilmaiya** [aws/aws-xray-sdk-go#36]
[Container] 2018/01/28 08:13:25 Running command go get -u github.com/aws/aws-xray-sdk-go/...
# github.com/aws/aws-xray-sdk-go/xray
../github.com/aws/aws-xray-sdk-go/xray/httptrace.go:199: unknown httptrace.ClientTrace field 'TLSHandshakeStart' in struct literal
../github.com/aws/aws-xray-sdk-go/xray/httptrace.go:202: unknown httptrace.ClientTrace field 'TLSHandshakeDone' in struct literal

Is there anything that has to be included to get this right.

**Comment by luluzhao** [comment]
@sunilmaiya , thank you for reaching out to us. Could you tell me how did you get this error message? Is just running "go get" or you are trying to create a segment? What is more, could you help me to check which version of Go you are currently using?

**Comment by sunilmaiya** [comment]
I am getting this error during codestar build, when the yml file gets parsed for dependency installation. 
I don't get this error during local installation of the package.

**Comment by luluzhao** [comment]
@sunilmaiya , `TLSHandshakeStart` and `TLSHandshakeDone` functions are only available for Go 1.8+. This should be the cause of your problem. Could you check the Go version when you are using codestar?
