### ISSUE TITLE
Versioning with Glide causing issues

### ISSUE THREAD

**Issue by uded** [aws/aws-xray-sdk-go#37]
It seems that the current [`glide.yaml`](/aws/aws-xray-sdk-go/blob/master/glide.yaml) is listing all dependencies without ranges. Which, in general, is absolutely acceptable. On the other hand, it creates a problem with cyclic, infinite combining of semver for dependency in a project which will try to use latest dependency of, for example, [AWS SDK for GO](https://github.com/aws/aws-sdk-go), currently in version `1.2.70`. I can assume that there are breaking changes between them (or maybe not), but in any case, this should be resolved this way or another. IMHO on the level of this project first...

**Comment by luluzhao** [comment]
@uded , thank you so much for reaching out to us. I understand your concern regarding the dependency. We should check the compatibility between our code and dependencies. I will add a range in version field and you will be able to see it in next release. The reason we didn't list the version range previously is that this is minor version update not major version which means there is no API level or breaking change. If there is a major version update, we definitely will mention it.

**Comment by alexbilbie** [comment]
@luluzhao do you have an updated timeframe when you might be able to resolve this?

**Comment by luluzhao** [comment]
@alexbilbie , thank you for your patience. Unfortunately, I don't have an exact timeframe for this issue since I am busy with another project right now. I will prioritize this issue in my backlog since it seems like it is not a difficult issue to fix. Sorry for this inconvenience.

**Comment by alexbilbie** [comment]
Would you accept a PR?

**Comment by luluzhao** [comment]
@alexbilbie , yes. We'd like to accept a PR. Feel free to send out a PR and I will take a look at it. Thank you.
