### ISSUE TITLE
DynamoDB table information and other meta not set

### ISSUE THREAD

**Issue by alexbilbie** [aws/aws-xray-sdk-go#4]
I'm seeing `aws` metadata in segments however the `table_name` and other properties aren't being set:

```js
"aws": {
  "consistent_read": null,
  "consumed_capacity": null,
  "operation": "GetItem",
  "projection_expression": null,
  "region": "eu-west-1",
  "request_id": "MNCJ6R6HEAMTOSCET28V5FD3MRVV4KQNSO5AEMVJF66Q9ASUAAJH",
  "retries": 0,
  "table_name": null
}
```

I'm following the guidance in this repos' README whereby calls to DynamoDB use the `WithContext` variation of the `GetItem` method.

 I'm not sure if this is a problem with this library or with the AWS Golang SDK.

**Comment by jamesdbowman** [comment]
Thanks for reporting this bug @alexbilbie. We've released version 0.9.2 to address this issue.
