### ISSUE TITLE
Remove the use of github.com/pkg/errors as its moved to Archived.

### ISSUE THREAD

**Issue by csg-kdeepak** [aws/aws-xray-sdk-go#452]
The code is making use of the github.com/pkg/errors. The package has been moved to Public Archive and not being maintained anymore. Should be replaced by an available public package.

**Comment by atshaw43** [comment]
Thanks for bringing this to our attention.

Our users could still be using passing errors as stack traces from this library. We translate those errors into exceptions which can then be added to a segment (see below). Removing this translation would change behavior and, therefore, be a breaking change for customer still using it. We will have to wait until a major version change before implementing this. I am going to close this for now. It is something we can look into when we do another major version change.

https://github.com/aws/aws-xray-sdk-go/blob/master/strategy/exception/default_exception_formatting_strategy.go#L155
