### ISSUE TITLE
Lambda to lambda tracing and displayed in the service map

### ISSUE THREAD

**Issue by rmossuk** [aws/aws-xray-sdk-go#46]
I have the API Gateway that calls Lamdba function 1 and that invokes lambda function 2 in Go. I want to see these 2 functions joined in the service map.

The only way i have been able to do this so far is to create a custom segment eg called "parent" and the create a subsegment from this context eg called "child". Then using client.InvokeWithContext to invoke the function 2 passing the "child" segment context.

```
sess := session.Must(session.NewSession()) client := lambda.New(sess, &aws.Config{Region: aws.String(region)})

xray.Configure(xray.Config{LogLevel: "trace"}) xray.AWS(client.Client)

ctx, seg := xray.BeginSegment(context.Background(), "Parent") ctx, subseg := xray.BeginSubsegment(ctx, "Child") result, _ := client.InvokeWithContext(ctx, &lambda.InvokeInput{FunctionName: aws.String(functionName), Payload: nil})

subseg.Close(nil) seg.Close(nil)

```
Problem is that this creates trace parent -> child in sevice map but also has function 1 too.

What is the best way to join these 2 functions on the service map please ? Note. I have more than 2 that i want to see linked up on the service map to show me my whole flow through lambdas.

Please help.

Thanks Rick

**Comment by luluzhao** [comment]
@rmossuk, thank you for contacting us regarding your question. I am not sure why you create "parent" segment and "child" subsegment to invoke function 2. If you have function 1's `context`, in your case, you should pass it into function 2 instead of creating segment manually by yourself.

**Comment by rmossuk** [comment]
@luluzhao   thank you for the help so far.   I have tried that but getting an error "runtime error: invalid memory address or nil pointer dereference"

Here is what i am trying to do:

here is my function 1 handler with context

`func Handler(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {`

And here i am trying to use that context

```
sess := session.Must(session.NewSession())
	
client := lambda.New(sess, &aws.Config{Region: aws.String(region)})

xray.Configure(xray.Config{LogLevel: "trace"})
xray.AWS(client.Client)

result, _ := client.InvokeWithContext(ctx, &lambda.InvokeInput{FunctionName: aws.String("xray-test-dev-child"), Payload: nil})
```

I get an error on the last line with "errorString: runtime error: invalid memory address or nil pointer dereference"

Any ideas what i am doing wrong ?

Thank you

**Comment by luluzhao** [comment]
@rmossuk sorry for the late response. After looking at your latest reply, I have two questions. First, You said you have two lambda functions and you want function 1 to invoke function 2. Have you created these two lambda functions by calling `CreateFunctionWithContext`? Second. How many `Handler` you wrote in your current application?

**Comment by awssandra** [comment]
Closing for now, please feel free to reopen if you have further issues.
Thank you!
