### ISSUE TITLE
Wrapping clients (SQS, Lambda) makes them doing nothing?

### ISSUE THREAD

**Issue by bubenkoff** [aws/aws-xray-sdk-go#47]
When I wrap aws service's client with xray.AWS looks like it stops functioning normally (does no real AWS API calls), nor the xray traces are reported
I however do see the xray's tracing in the log (so i of course use WithContext versions of the calls)

**Comment by luluzhao** [comment]
@bubenkoff, thank you for contacting us regarding your issue. Have you take a look at README? There is an example to show how to instrument aws service' client with xray.AWS(). You said you see the tracing in the log and I am wondering you see the exact segment SDK generated? If you saw the real segment in log file and you didn't see the service map in console, there might be a daemon issue on your local host. What is more, could you also attached the wrap function you wrote at here? It will help us to debug your issue. Thank you.

**Comment by bubenkoff** [comment]
@luluzhao I use it inside lambda, so daemon is not needed to be runnning right?
> On AWS Lambda and AWS Elastic Beanstalk, use those services' integration with X-Ray to run the daemon. Lambda runs the daemon automatically any time a function is invoked for a sampled request
and this is the log i get:
```
START RequestId: bcc16f09-2d7f-11e8-8342-ef40bad6c7cf Version: $LATEST
1521688728712815713 [Trace] Beginning segment named facade
1521688728719954193 [Trace] Closing subsegment named response
1521688728719997936 [Trace] Closing subsegment named attempt
1521688728720013044 [Trace] Beginning subsegment named unmarshal
1521688728720173892 [Trace] Closing subsegment named unmarshal
1521688728720197518 [Trace] Closing subsegment named sqs
1521688728720201484 [Trace] emit lambda subsegment named: sqs
1521688728720225034 [Trace] Beginning segment named facade
1521688728720229789 [Trace] Beginning subsegment named lambda
1521688728720240092 [Trace] Beginning subsegment named marshal
1521688728720270573 [Trace] Closing subsegment named marshal
1521688728720276872 [Trace] Beginning subsegment named attempt
1521688728823854383 [Trace] Closing subsegment named attempt
1521688728823874520 [Trace] Beginning subsegment named unmarshal
1521688728823897329 [Trace] Closing subsegment named unmarshal
1521688728823930689 [Trace] Closing subsegment named lambda
1521688728823935230 [Trace] emit lambda subsegment named: lambda
END RequestId: bcc16f09-2d7f-11e8-8342-ef40bad6c7cf
REPORT RequestId: bcc16f09-2d7f-11e8-8342-ef40bad6c7cf	Duration: 193.95 ms	Billed Duration: 200 ms 	Memory Size: 1024 MB	Max Memory Used: 23 MB
```

so it looks like the problem is with the automatic daemon in lambda?
but then still, daemon is not the one who does real calls to the api's like lambda invocation, daemon only sends stats to aws xray.
So still not clear why once wrapped with xray.AWS clients stop working as they should. Is the wrapped routine safe? Because I only wrap it only on the cold start

**Comment by luluzhao** [comment]
@bubenkoff sorry for misleading information in the previous reply. You are right, if you are using Lambda or Elastic Beanstalk, you don't have to install daemon and start daemon by yourself. The reason I am asking in previous reply is that you didn't mention you are using Lambda. 

Could you pull the latest version of our Go SDK and run it again? We had a bug in Lambda(https://github.com/aws/aws-xray-sdk-go/commit/0b5dfa3c8c76d5cccdd216d17db0d525052b548c) and We already fix it. Based on the log file you attached. It seems like the subsegments haven't been emitted so that is why you cannot see it and I think that PR will fix this issue. What is more, xray functions should be used inside lambda `Handler` function. We didn't support to call it inside `init` function.

**Comment by bubenkoff** [comment]
@luluzhao thanks, will check and get back to you
about the use of xray in the `init` - I don't use it there, I mentioned cold start as I use global state to keep the aws session and aws service structs and share them between the invocations. So on first invocation, inside Handler, the services are set up.

**Comment by bubenkoff** [comment]
@luluzhao 
```
Could you pull the latest version of our Go SDK and run it again? We had a bug in Lambda(0b5dfa3) 
```
it's quite impossible to do it, as go sdk is v1.13.23 and aws-xray-sdk-go depends on github.com/aws/aws-sdk-go of 1.10.x

**Comment by luluzhao** [comment]
@bubenkoff, I am sorry for misleading information in my previous reply. I said `our Go SDK` which means `AWS X-Ray Go SDK`. We did a new release recently and the version should be `v1.0.0-rc.2`.

**Comment by bubenkoff** [comment]
ah ok thanks, will get back to you

**Comment by awssandra** [comment]
Closing for now, please feel free to reopen if you continue to experience issues.
Thank you!
