### ISSUE TITLE
Custom Subsegment options

### ISSUE THREAD

**Issue by DaveBlooman** [aws/aws-xray-sdk-go#5]
The current subsegment option is fine if you want to wrap you function inside xray and not return data.  If you do, you'll have to scope the data outside the xray wrapper.  Can I suggest a simpler subsegment record be introduced that allows for a function name to passed and perhaps annotations.  A use case maybe reading data from a file and unmarshalling JSON, then processing that data.

**Comment by dlsniper** [comment]
I think that the current way to of how ` xray.Capture ` and ` xray.CaptureAsync ` works shows that maybe those functions shouldn't be provided. The interface is rather awkward to use and I think the example in #1 shows that it can be done a lot better.

**Comment by luluzhao** [comment]
Hi @DaveBlooman , thank you for reaching out to us. This is way we designed for Capture and CaptureAsync method and like @dlsniper said, you can use CreateSegment or CreateSubsegment method which do not require a function if that can help your case.
