### ISSUE TITLE
Handle null segment in SQL

### ISSUE THREAD

**Issue by unosoft** [aws/aws-xray-sdk-go#63]
I have my missing context strategy to be a nop (I want to ignore instances where the context does not have a valid segment). Even with the right configuration the application crashes due to a null pointer.

Something like this would solve the problem.

```
diff --git a/xray/sql.go b/xray/sql.go
index d463672..88954cc 100644
--- a/xray/sql.go
+++ b/xray/sql.go
@@ -150,6 +150,9 @@ func (db *DB) SetMaxOpenConns(n int) { db.db.SetMaxOpenConns(n) }
 
 func (db *DB) populate(ctx context.Context, query string) {
        seg := GetSegment(ctx)
+       if seg == nil {
+               return
+       }
 
        seg.Lock()
        seg.Namespace = "remote"
@@ -191,6 +194,9 @@ func (stmt *Stmt) populate(ctx context.Context, query string) {
        stmt.db.populate(ctx, query)
 
        seg := GetSegment(ctx)
+       if seg == nil {
+               return
+       }
        seg.Lock()
        seg.GetSQL().Preparation = "statement"
        seg.Unlock()

```

**Comment by luluzhao** [comment]
@unosoft 

Sorry for the late response. Our SDK should handle nil pointer exceptions by implementing ContextMissingStrategy. You're welcome to send us a PR regarding the fix. If not, we will add this change in to our backlog and make sure release ASAP.

**Comment by luluzhao** [comment]
@unosoft ,

Sorry for my confusing reply. We knew you were doing the correct thing and our code indeed should catch up nil pointer exception. We should modify our code not you. :)

**Comment by haotianw465** [comment]
This is fixed as part of rc9 release.
