### ISSUE TITLE
Allow AWS_XRAY_DAEMON_ADDRESS or DaemonAddr to use a hostname

### ISSUE THREAD

**Issue by dgiamanco-fortmason** [aws/aws-xray-sdk-go#70]
The example ecs task definition on https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html uses a hostname instead of an IP address for the AWS_XRAY_DAEMON_ADDRESS environment variable. This causes an error in daemoncfg/daemon_config.go:128 where the address is assumed to be an IP. 

I've locally added net.LookupIP() to translate the hostname to IP address but this might be a good addition to the SDK as well.

**Comment by yogiraj07** [comment]
Hi @dgiamanco-fortmason ,
Thanks for the feedback. We are working on the issue. I think `net.ParseIp()` : [Link](https://github.com/aws/aws-xray-sdk-go/blob/master/daemoncfg/daemon_config.go#L128) was unnecessary that prevented hostname parsing.

We can rely on underline UDP and TCP resolver, to resolve IP/Hostname and propagate errors, if any: [Link](https://github.com/aws/aws-xray-sdk-go/blob/master/daemoncfg/daemon_config.go#L147) 

Best,
Yogi

**Comment by dgiamanco-fortmason** [comment]
That should work, thanks for looking into it.
