### ISSUE TITLE
Data race when use http client

### ISSUE THREAD

**Issue by domashevskiy** [aws/aws-xray-sdk-go#71]
Reproduced on:
- SDK version: V1.0.0-rc.8.
- GO version: go1.11.1 linux/amd64

When build with - race flag, data race warning occurs upon sending http request:

WARNING: DATA RACE
Read at 0x00c000a201b0 by goroutine 56:
  vendor/github.com/aws/aws-xray-sdk-go/xray.(*HTTPSubsegments).GotFirstResponseByte()
      vendor/github.com/aws/aws-xray-sdk-go/xray/httptrace.go:159 +0x47
  privacyapi/vendor/github.com/aws/aws-xray-sdk-go/xray.NewClientTrace.func10()
      vendor/github.com/aws/aws-xray-sdk-go/xray/httptrace.go:212 +0x41
  net/http.http2traceFirstResponseByte()
      /usr/local/go/src/net/http/h2_bundle.go:3035 +0x7d
  net/http.(*http2clientConnReadLoop).processHeaders()
      /usr/local/go/src/net/http/h2_bundle.go:8360 +0x52a
  net/http.(*http2clientConnReadLoop).run()
      /usr/local/go/src/net/http/h2_bundle.go:8292 +0x87d
  net/http.(*http2ClientConn).readLoop()
      /usr/local/go/src/net/http/h2_bundle.go:8189 +0x8c

Previous write at 0x00c000a201b0 by main goroutine:
  vendor/github.com/aws/aws-xray-sdk-go/xray.(*HTTPSubsegments).WroteRequest()
      vendor/github.com/aws/aws-xray-sdk-go/xray/httptrace.go:152 +0x156
 vendor/github.com/aws/aws-xray-sdk-go/xray.NewClientTrace.func9()
      vendor/github.com/aws/aws-xray-sdk-go/xray/httptrace.go:209 +0x55
  net/http.http2traceWroteRequest()

**Comment by luluzhao** [comment]
@domashevskiy , sorry for the late response. I merged @t-yuki PR and will make sure bring this fix to next release.
