### ISSUE TITLE
Replace glide

### ISSUE THREAD

**Issue by emirb** [aws/aws-xray-sdk-go#73]
As the [documentation mentions](https://github.com/Masterminds/glide#golang-dep), using Glide for dependency management is not recommended anymore as `dep` is available for some time now. 

I would propose moving to `dep` or even better to Go modules (previously known as `vgo`) which are available since 1.11 release.

**Comment by BHunter2889** [comment]
I would like to add a subtask to this:

- [ ]  fix versioning to meet `dep` standards by removing  `-rc` tagging practice which prevents `dep` from getting latest version.

**Comment by emirb** [comment]
@luluzhao Are you going to skip `dep` support and skip to Go modules directly?

**Comment by luluzhao** [comment]
Hello @emirb , after reading [Go package management tools wiki](https://github.com/golang/go/wiki/PackageManagementTools), I found out Go111Module became the "official experiment" which was "dep tool" before. Thanks for pointing out this and we are definitely going to mark Go modules as priority to solve glide issue. Please stay in tuned.

**Comment by chrisradek** [comment]
The SDK now supports `dep` and go modules as of [V1.0.0-rc.11](https://github.com/aws/aws-xray-sdk-go/releases/tag/V1.0.0-rc.11).

Removing the `-rc` tag will be a separate task once the SDK is no longer in a release candidate stage.
