### ISSUE TITLE
Add log for completion http request in logs

### ISSUE THREAD

**Issue by jason-riddle** [aws/aws-xray-sdk-go#75]
When the loglevel has been set to trace like so:

```
xray.Configure(xray.Config{LogLevel: "trace"})
```

One would expect information about when the request is actually sent to be added to the logs. However, the last thing that gets logged is the json representation of the trace. What I would like to see is additional information such as the ip address the xray client sdk tried to send information to and whether the response was successful or failure. Something as brief as "Connection to X.X.X.X with protocol udp/tcp was successful/unsuccessful" would be great! The usecase is to just have more debugging information available if the xray client sdk is misconfigured. Right now everything just works, but if I were to say misconfigure my firewall/security group/iptables or apply too strict of a selinux policy, it would be great to have the additional xray sdk client logs to help troubleshoot this.

**Comment by luluzhao** [comment]
Hello @jason-riddle , thank you for your suggestions. Currently, XRay Go SDK doesn't catch connection error so that we cannot log such information like you mentioned above. However, we should catch errors or exceptions if there is a udp connection error. I will add this feature into our backlog and make sure we will address it soon. Please stay tuned.

**Comment by haotianw465** [comment]
Hi @jason-riddle , we do have `info` level log statement if the udp is successfully dialed: https://github.com/aws/aws-xray-sdk-go/blob/master/xray/emitter.go#L43-L46

The SDK tries to resolve the daemon address during configuration and the config method return all the errors https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L149 occurred during configuration. The caller can handle errors by logging it (and chose log level) or by panic and it is up to the user. Do you think this solution works better for you?

**Comment by jason-riddle** [comment]
> we do have info level log statement if the udp is successfully dialed: https://github.com/aws/aws-xray-sdk-go/blob/master/xray/emitter.go#L43-L46

There isn't a line 43-46 in this file. Also, I don't see a log statement anywhere in this file.

> The SDK tries to resolve the daemon address during configuration and the config method return all the errors https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L149

Line 149 links to a new line. I'm guessing you meant this line: https://github.com/aws/aws-xray-sdk-go/blob/9779f16ea01fdfc11c54971ed8547dbaa442bb42/xray/config.go#L144. I've added the commit hash just to be sure. That's nice that it returns all of the errors.

> The caller can handle errors by logging it (and chose log level) or by panic and it is up to the user. Do you think this solution works better for you?

Are you asking if one approach is preferred over the other? If that's the case, I'd prefer logging as it's backwards compatible and the user doesn't have to add new code to handle the panic.
