### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by Cosaquee** [aws/aws-xray-sdk-go#77]
In our CI we can see this error:

```
[Container] 2019/01/07 10:50:59 Running command go get github.com/aws/aws-xray-sdk-go/...
# github.com/aws/aws-xray-sdk-go/strategy/exception
/go/src/github.com/aws/aws-xray-sdk-go/strategy/exception/default_exception_formatting_strategy.go:148:25: cannot convert frame (type "github.com/pkg/errors".Frame) to type uintptr
```

Running the same command inside official Go container for versions

* 1.11
```
~/go/src/github.com/cosaquee/xray-demo(master ✗) docker run -it --rm golang:1.11
Unable to find image 'golang:1.11' locally
1.11: Pulling from library/golang
cd8eada9c7bb: Already exists
c2677faec825: Already exists
fcce419a96b1: Already exists
045b51e26e75: Already exists
70a7003e9fe9: Already exists
751b6f060321: Pull complete
462a907acb44: Pull complete
Digest: sha256:4f1cd313c3d59faa0ca93910f9d853bd74be7afbf6f6997aee06924415ec7dc9
Status: Downloaded newer image for golang:1.11
root@c2fdab63256d:/go# go get -u github.com/aws/aws-xray-sdk-go/...
# github.com/aws/aws-xray-sdk-go/strategy/exception
src/github.com/aws/aws-xray-sdk-go/strategy/exception/default_exception_formatting_strategy.go:148:25: cannot convert frame (type "github.com/pkg/errors".Frame) to type uintptr
root@c2fdab63256d:/go#
```

* 1.10
```
/go/src/github.com/cosaquee/xray-demo(master ✗) docker run -it --rm golang:1.10
Unable to find image 'golang:1.10' locally
1.10: Pulling from library/golang
cd8eada9c7bb: Already exists
c2677faec825: Pull complete
fcce419a96b1: Pull complete
045b51e26e75: Pull complete
70a7003e9fe9: Pull complete
057d7cdb2121: Pull complete
a44377be7095: Pull complete
Digest: sha256:6d006a643599f44b08b0d692102bbb35e12dbd968c68cf0d6c10da9afda9d98d
Status: Downloaded newer image for golang:1.10
root@fc8f80227176:/go# go get -u github.com/aws/aws-xray-sdk-go/...
# github.com/aws/aws-xray-sdk-go/strategy/exception
src/github.com/aws/aws-xray-sdk-go/strategy/exception/default_exception_formatting_strategy.go:148:25: cannot convert frame (type "github.com/pkg/errors".Frame) to type uintptr
```

We are not using Glide for dependencies management so we are running plain `go get` commands to download all the packages. As we can see there is an error when downloading this package.

```
	// We also accept github.com/pkg/errors style stack traces for ease of use
	if err, ok := err.(interface {
		StackTrace() errors.StackTrace
	}); ok {
		for _, frame := range err.StackTrace() {
			s = append(s, uintptr(frame))
		}
	}
```

The current master of https://github.com/pkg/errors is breaking the code above. [This commit](https://github.com/pkg/errors/commit/4f47277723cbe176eaef3bccb66a69de7a531157#diff-7dc02266d93e96cde6ba279eadbcac8fR12) has changed type of frame from `uintptr` to `runtime.Frame`.

The master is currently broken on Travis also, but I'm not sure if it is related to this issue.

I'm not sure how to handle this situation without rebuilding `aws-xray-sdk-go` with the `pkg/errors` version https://github.com/pkg/errors/releases/tag/v0.8.1

**Comment by dan-lind** [comment]
Running into the exact same issue

**Comment by yogiraj07** [comment]
Hi @Cosaquee ,
Thanks for reporting the issue. We have an issue [#73](https://github.com/aws/aws-xray-sdk-go/issues/73)  reported for moving away from glide. Currently we support [0.8.x](https://github.com/aws/aws-xray-sdk-go/blob/master/glide.yaml#L6) of the `errors` package and this will be solved as a part of migration away from glide dependency management.

Travis is broken due to different reason, however, the current X-Ray Go SDK release is stable.

Best,
Yogi

**Comment by Cosaquee** [comment]
I can confirm that after https://github.com/pkg/errors/pull/193 our CI is green. I still need to deploy functions that are using this package but it seems to be ok.
