### ISSUE TITLE
AddError records fault(5xx) instead of error(4xx)

### ISSUE THREAD

**Issue by rangaataws** [aws/aws-xray-sdk-go#84]
**Expected behavior:**
To be in sync with other language SDKs, Go SDK should have two methods,
AddError -> logs an 4XX error with flag `fault = false`
AddFault -> logs an 5XX error with flag `fault = true`
By doing this, in X-Ray console, we can differentiate the errors by colors. Faults are shown in red color, errors are shown in yellow color.

**Actual behavior:**
AddError -> logs errors with flag fault=true

**Comment by luluzhao** [comment]
In Go, there is no conception of exception. However, in order to keep consistency of the feature across of all SDKs, we implemented exception strategy but the method name called `AddError`.

**Comment by rangaataws** [comment]
Thanks for the response. When I find time, I will try a few more ways to see if it is a problem to me or not.
