### ISSUE TITLE
Fix flaky CI tests

### ISSUE THREAD

**Issue by chrisradek** [aws/aws-xray-sdk-go#94]
The `TestLambdaSegmentEmit` test in `lambda_test.go` appears to be flaky:
https://travis-ci.org/aws/aws-xray-sdk-go/jobs/510026094
This test has failed a couple times in different builds since we reactivated travis.

We've also seen an `invalid memory address or nil pointer dereference` error in the `TestMySQL` test once:
https://travis-ci.org/aws/aws-xray-sdk-go/jobs/510026091

**Comment by luluzhao** [comment]
Update:

SQL unit test is fixed by this PR: https://github.com/aws/aws-xray-sdk-go/pull/121

still need to get Lambda unit test fixed.
