### ISSUE TITLE
Conn( ) support

### ISSUE THREAD

**Issue by pjebs** [aws/aws-xray-sdk-go#98]
Can xray please support `Conn`: https://golang.org/pkg/database/sql/#DB.Conn

https://godoc.org/github.com/aws/aws-xray-sdk-go/xray#DB

This is of little value without support for obtaining an exclusive connection.

**Comment by luluzhao** [comment]
Hello @pjebs, thank you so much for contacting us. We will add this one into our backlog. In the meantime, we also accept PRs. If you would like to send us PR, we are happy to help you.
