### ISSUE TITLE
Resource leak when HTTP handler panics

### ISSUE THREAD

**Issue by silverspace** [aws/aws-xray-sdk-go#99]
The existing implementation of `func Handler(sn SegmentNamer, h http.Handler) http.Handler` has a resource leak if the passed in `http.Handler` panics, since `seg.Close(nil)` is never invoked. To avoid this, please change:
https://github.com/aws/aws-xray-sdk-go/blob/master/xray/handler.go#L179
to be 
```
		defer seg.Close(nil)
```
after acquiring the segment.

**Comment by bhautikpip** [comment]
I am closing this issue since we have pushed out a fix for this issue in this release (https://github.com/aws/aws-xray-sdk-go/releases/tag/v1.0.0-rc.15). Feel free to open another issue if you think it's not addressed.
